# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x10\n\x0eGetUserRequest\"-\n\x0fGetUserResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xdb\x02\n\x05Users\x12;\n\x08GetUsers\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_GETUSERREQUEST = DESCRIPTOR.message_types_by_name['GetUserRequest']
_GETUSERRESPONSE = DESCRIPTOR.message_types_by_name['GetUserResponse']
_GETUSERBYIDREQUEST = DESCRIPTOR.message_types_by_name['GetUserByIdRequest']
_GETUSERBYIDRESPONSE = DESCRIPTOR.message_types_by_name['GetUserByIdResponse']
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_CREATEUSERRESPONSE = DESCRIPTOR.message_types_by_name['CreateUserResponse']
_UPDATEUSERREQUEST = DESCRIPTOR.message_types_by_name['UpdateUserRequest']
_UPDATEUSERRESPONSE = DESCRIPTOR.message_types_by_name['UpdateUserResponse']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteUserRequest']
_DELETEUSERRESPONSE = DESCRIPTOR.message_types_by_name['DeleteUserResponse']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.User)
  })
_sym_db.RegisterMessage(User)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

GetUserResponse = _reflection.GeneratedProtocolMessageType('GetUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUserResponse)
  })
_sym_db.RegisterMessage(GetUserResponse)

GetUserByIdRequest = _reflection.GeneratedProtocolMessageType('GetUserByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERBYIDREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUserByIdRequest)
  })
_sym_db.RegisterMessage(GetUserByIdRequest)

GetUserByIdResponse = _reflection.GeneratedProtocolMessageType('GetUserByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERBYIDRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUserByIdResponse)
  })
_sym_db.RegisterMessage(GetUserByIdResponse)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.CreateUserResponse)
  })
_sym_db.RegisterMessage(CreateUserResponse)

UpdateUserRequest = _reflection.GeneratedProtocolMessageType('UpdateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UpdateUserRequest)
  })
_sym_db.RegisterMessage(UpdateUserRequest)

UpdateUserResponse = _reflection.GeneratedProtocolMessageType('UpdateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UpdateUserResponse)
  })
_sym_db.RegisterMessage(UpdateUserResponse)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

DeleteUserResponse = _reflection.GeneratedProtocolMessageType('DeleteUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.DeleteUserResponse)
  })
_sym_db.RegisterMessage(DeleteUserResponse)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=22
  _USER._serialized_end=87
  _GETUSERREQUEST._serialized_start=89
  _GETUSERREQUEST._serialized_end=105
  _GETUSERRESPONSE._serialized_start=107
  _GETUSERRESPONSE._serialized_end=152
  _GETUSERBYIDREQUEST._serialized_start=154
  _GETUSERBYIDREQUEST._serialized_end=186
  _GETUSERBYIDRESPONSE._serialized_start=188
  _GETUSERBYIDRESPONSE._serialized_end=236
  _CREATEUSERREQUEST._serialized_start=238
  _CREATEUSERREQUEST._serialized_end=284
  _CREATEUSERRESPONSE._serialized_start=286
  _CREATEUSERRESPONSE._serialized_end=333
  _UPDATEUSERREQUEST._serialized_start=335
  _UPDATEUSERREQUEST._serialized_end=381
  _UPDATEUSERRESPONSE._serialized_start=383
  _UPDATEUSERRESPONSE._serialized_end=430
  _DELETEUSERREQUEST._serialized_start=432
  _DELETEUSERREQUEST._serialized_end=463
  _DELETEUSERRESPONSE._serialized_start=465
  _DELETEUSERRESPONSE._serialized_end=512
  _USERS._serialized_start=515
  _USERS._serialized_end=862
# @@protoc_insertion_point(module_scope)
